name: multiqc
description: Aggregate results from bioinformatics analyses across many samples 
  into a single report
keywords:
- QC
- bioinformatics tools
- Beautiful stand-alone HTML report
tools:
- multiqc:
    description: |
      MultiQC searches a given directory for analysis logs and compiles a HTML report.
      It's a general use tool, perfect for summarising the output from numerous bioinformatics tools.
    homepage: https://multiqc.info/
    documentation: https://multiqc.info/docs/
    licence: ["GPL-3.0-or-later"]
    identifier: biotools:multiqc
input:
- multiqc_files:
    type: file
    description: |
      List of reports / files recognised by MultiQC, for example the html and zip output of FastQC
    ontologies: []
- multiqc_config:
    type: file
    description: Optional config yml for MultiQC
    pattern: "*.{yml,yaml}"
    ontologies:
    - edam: http://edamontology.org/format_3750     # YAML
- extra_multiqc_config:
    type: file
    description: Second optional config yml for MultiQC. Will override common 
      sections in multiqc_config.
    pattern: "*.{yml,yaml}"
    ontologies:
    - edam: http://edamontology.org/format_3750     # YAML
- multiqc_logo:
    type: file
    description: Optional logo file for MultiQC
    pattern: "*.{png}"
    ontologies: []
- replace_names:
    type: file
    description: |
      Optional two-column sample renaming file. First column a set of
      patterns, second column a set of corresponding replacements. Passed via
      MultiQC's `--replace-names` option.
    pattern: "*.{tsv}"
    ontologies:
    - edam: http://edamontology.org/format_3475     # TSV
- sample_names:
    type: file
    description: |
      Optional TSV file with headers, passed to the MultiQC --sample_names
      argument.
    pattern: "*.{tsv}"
    ontologies:
    - edam: http://edamontology.org/format_3475     # TSV
output:
  report:
  - "*multiqc_report.html":
      type: file
      description: MultiQC report file
      pattern: "multiqc_report.html"
      ontologies: []
  data:
  - "*_data":
      type: directory
      description: MultiQC data dir
      pattern: "multiqc_data"
  plots:
  - "*_plots":
      type: file
      description: Plots created by MultiQC
      pattern: "*_data"
      ontologies: []
  versions:
  - versions.yml:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
      ontologies:
      - edam: http://edamontology.org/format_3750     # YAML
authors:
- "@abhi18av"
- "@bunop"
- "@drpatelh"
- "@jfy133"
maintainers:
- "@abhi18av"
- "@bunop"
- "@drpatelh"
- "@jfy133"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/multiqc:1.32--d58f60e4deb769bf
      buildId: bd-d58f60e4deb769bf_1
      scanId: sc-d76ac07493e940b4_7
    linux/arm64:
      name: community.wave.seqera.io/library/multiqc:1.32--193776baee4194db
      buildId: bd-193776baee4194db_1
      scanId: sc-86caded0bff8246e_4
  singularity:
    linux/amd64:
      name: 
        oras://community.wave.seqera.io/library/multiqc:1.32--e649ffa094d1ef4a
      buildId: bd-e649ffa094d1ef4a_1
      https: 
        https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/8c/8c6c120d559d7ee04c7442b61ad7cf5a9e8970be5feefb37d68eeaa60c1034eb/data
    linux/arm64:
      name: 
        oras://community.wave.seqera.io/library/multiqc:1.32--aee0064f5570ef22
      buildId: bd-aee0064f5570ef22_1
      https: 
        https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/f0/f02c59ebf6e9a00aa954ee8188a4ecc5c743e18f40b9215a242f67606a00f9cf/data
  conda:
    linux/amd64:
      lock_file: 
        modules/nf-core/multiqc/.conda-lock/linux-amd64-bd-d58f60e4deb769bf_1.txt
    linux/arm64:
      lock_file: 
        modules/nf-core/multiqc/.conda-lock/linux-arm64-bd-193776baee4194db_1.txt
