name: multiqc
description: Aggregate results from bioinformatics analyses across many samples into
  a single report
keywords:
  - QC
  - bioinformatics tools
  - Beautiful stand-alone HTML report
tools:
  - multiqc:
      description: |
        MultiQC searches a given directory for analysis logs and compiles a HTML report.
        It's a general use tool, perfect for summarising the output from numerous bioinformatics tools.
      homepage: https://multiqc.info/
      documentation: https://multiqc.info/docs/
      licence: ["GPL-3.0-or-later"]
      identifier: biotools:multiqc
input:
  - multiqc_files:
      type: file
      description: |
        List of reports / files recognised by MultiQC, for example the html and zip output of FastQC
      ontologies: []
  - multiqc_config:
      type: file
      description: Optional config yml for MultiQC
      pattern: "*.{yml,yaml}"
      ontologies:
        - edam: http://edamontology.org/format_3750 # YAML
  - extra_multiqc_config:
      type: file
      description: Second optional config yml for MultiQC. Will override common sections
        in multiqc_config.
      pattern: "*.{yml,yaml}"
      ontologies:
        - edam: http://edamontology.org/format_3750 # YAML
  - multiqc_logo:
      type: file
      description: Optional logo file for MultiQC
      pattern: "*.{png}"
      ontologies: []
  - replace_names:
      type: file
      description: |
        Optional two-column sample renaming file. First column a set of
        patterns, second column a set of corresponding replacements. Passed via
        MultiQC's `--replace-names` option.
      pattern: "*.{tsv}"
      ontologies:
        - edam: http://edamontology.org/format_3475 # TSV
  - sample_names:
      type: file
      description: |
        Optional TSV file with headers, passed to the MultiQC --sample_names
        argument.
      pattern: "*.{tsv}"
      ontologies:
        - edam: http://edamontology.org/format_3475 # TSV
output:
  report:
    - "*multiqc_report.html":
        type: file
        description: MultiQC report file
        pattern: "multiqc_report.html"
        ontologies: []
  data:
    - "*_data":
        type: directory
        description: MultiQC data dir
        pattern: "multiqc_data"
  plots:
    - "*_plots":
        type: file
        description: Plots created by MultiQC
        pattern: "*_data"
        ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
containers:
    docker:
        linux_amd64:
            name: community.wave.seqera.io/library/multiqc:1.32--d58f60e4deb769bf
            build_id: d58f60e4deb769bf
            scan_id: 6fc310277b74
        linux_arm64:
            name: community.wave.seqera.io/library/multiqc:1.32--d58f60e4deb769bf
            build_id: d58f60e4deb769bf
            scan_id: d9a1db848b9b
    singularity:
        linux_amd64:
            name: oras://community.wave.seqera.io/library/multiqc:1.32--d58f60e4deb769bf
            https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/8c/8c6c120d559d7ee04c7442b61ad7cf5a9e8970be5feefb37d68eeaa60c1034eb/data
            build_id: d58f60e4deb769bf
        linux_arm64:
            name: oras://community.wave.seqera.io/library/multiqc:1.32--d58f60e4deb769bf
            https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/8c/8c6c120d559d7ee04c7442b61ad7cf5a9e8970be5feefb37d68eeaa60c1034eb/data
            build_id: d58f60e4deb769bf
    conda:
        linux_amd64:
            lock file: https://wave.seqera.io/v1alpha1/builds/5cfd0f3cb6760c42_1/condalock
        linux_arm64:
            lock file: https://wave.seqera.io/v1alpha1/builds/d3caca66b4f3d3b0_1/condalock
authors:
  - "@abhi18av"
  - "@bunop"
  - "@drpatelh"
  - "@jfy133"
maintainers:
  - "@abhi18av"
  - "@bunop"
  - "@drpatelh"
  - "@jfy133"
