repository_type: pipeline
nf_core_version: 2.14.1
bump_version: null
lint:
  files_exist:
    - .github/workflows/awsfulltest.yml
    - .github/workflows/awstest.yml
    - conf/modules.config
  files_unchanged:
    - .gitignore
    - .github/workflows/linting.yml
    - assets/nf-core-sarek_logo_light.png
    - docs/images/nf-core-sarek_logo_dark.png
    - docs/images/nf-core-sarek_logo_light.png
  modules_config: false
  template_strings: false
org_path: null
template:
  author: TEST
  description: An open-source analysis pipeline to detect germline or somatic variants
    from whole genome or targeted sequencing
  force: false
  is_nfcore: true
  name: testpipeline
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0.0
update: null
