name: nf-core download
on:
  push:
  pull_request:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1

      - uses: actions/setup-python@v3
        with:
          python-version: "3.7"
          architecture: "x64"
      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nf-core

      - name: Download the pipeline
        env:
          NXF_SINGULARITY_CACHEDIR: ./
        run: nf-core download sarek -r dev -c singularity --singularity-cache-copy -x none --force -o test

      - name: Run the downloaded pipeline
        env:
          NXF_SINGULARITY_CACHEDIR: ./
        run: nextflow run test/workflow -profile test,singularity --outdir ./results
