name: nf-core NF latest-everything comment
# This workflow is triggered after the nf-core CI action is complete
# It posts an automated comment to the PR, even if the PR is coming from a fork

on:
  workflow_run:
    workflows: ["nf-core CI"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        id: pr_number
        run: echo "pr_number=${{ github.event.number }}" >> $GITHUB_OUTPUT

      - name: Post PR comment
        uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728 # v2
        if: ${{ github.event.workflow_run.steps.run-test.outcome == 'failure' }}
        with:
          GITHUB_TOKEN: ${{ secrets.nf_core_bot_auth_token }}
          number: ${{ steps.pr_number.outputs.pr_number }}
          message: |
            Pipeline run failed with Nextflow version ${{ github.event.workflow_run.matrix.NXF_VER }} on ${{ github.event.workflow_run.matrix.profile }}.
            `latest-everything` includes Nextflow edge releases, which can cause issues, when freshly released.
            Please check the [#pipeline-maintainers channel on Slack](https://nfcore.slack.com/archives/C04QR0T3G3H) if there is an issue with this Nextflow version.